// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "SSC 2023",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "SSC 2023",
            targets: ["AppModule"],
            bundleIdentifier: "du.yuhan.SSC-2023",
            teamIdentifier: "SMB4V4XL5Q",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .moon),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ],
            capabilities: [
                .camera(purposeString: "Allow access to capture textures"),
                .photoLibrary(purposeString: "Allow access to save textures")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
